name: Build and Deploy Angular App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Create environment.prod.ts
        run: |
          echo "export const environment = {" > src/environments/environment.prod.ts
          echo "  production: true," >> src/environments/environment.prod.ts
          echo "  firebaseConfig: '${{ secrets.FIREBASE_DETAILS }}'" >> src/environments/environment.prod.ts
          echo "  discordConfig: '${{ secrets.DISCORD_DETAILS }}'" >> src/environments/environment.prod.ts
          echo "};" >> src/environments/environment.prod.ts

      - name: Build Angular App
        run: npm run build --configuration=production
