on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Imposta le variabili d'ambiente dai GitHub Secrets
      - name: Set Firebase environment variables
        run: |
          echo "FIREBASE_APIKEY=${{ secrets.FIREBASE_APIKEY }}" >> $GITHUB_ENV
          echo "FIREBASE_APPID=${{ secrets.FIREBASE_APPID }}" >> $GITHUB_ENV
          echo "FIREBASE_AUTHDOMAIN=${{ secrets.FIREBASE_AUTHDOMAIN }}" >> $GITHUB_ENV
          echo "FIREBASE_MEASUREMENTID=${{ secrets.FIREBASE_MEASUREMENTID }}" >> $GITHUB_ENV
          echo "FIREBASE_MESSAGESENDERID=${{ secrets.FIREBASE_MESSAGESENDERID }}" >> $GITHUB_ENV
          echo "FIREBASE_PROJECTID=${{ secrets.FIREBASE_PROJECTID }}" >> $GITHUB_ENV
          echo "FIREBASE_STORAGEBUCKET=${{ secrets.FIREBASE_STORAGEBUCKET }}" >> $GITHUB_ENV

      # Sostituzione delle variabili nei file di configurazione
      - name: Replace Firebase environment variables in config
        run: |
          sed -i "s/{{FIREBASE_API_KEY}}/${{ secrets.FIREBASE_APIKEY }}/g" src/environments/environment.prod.ts
          sed -i "s/{{FIREBASE_AUTH_DOMAIN}}/${{ secrets.FIREBASE_AUTHDOMAIN }}/g" src/environments/environment.prod.ts
          sed -i "s/{{FIREBASE_PROJECT_ID}}/${{ secrets.FIREBASE_PROJECTID }}/g" src/environments/environment.prod.ts
          sed -i "s/{{FIREBASE_STORAGE_BUCKET}}/${{ secrets.FIREBASE_STORAGEBUCKET }}/g" src/environments/environment.prod.ts
          sed -i "s/{{FIREBASE_MESSAGING_SENDER_ID}}/${{ secrets.FIREBASE_MESSAGESENDERID }}/g" src/environments/environment.prod.ts
          sed -i "s/{{FIREBASE_APP_ID}}/${{ secrets.FIREBASE_APPID }}/g" src/environments/environment.prod.ts
          sed -i "s/{{FIREBASE_MEASUREMENT_ID}}/${{ secrets.FIREBASE_MEASUREMENTID }}/g" src/environments/environment.prod.ts

      # Install dependencies
      - name: Install dependencies
        run: |
          npm install

      # Build the app
      - name: Build the app
        run: |
          npm run build -- --configuration production



      



# name: Deploy Production

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v4

#       - name: Setup Node.js
#         uses: actions/setup-node@v4
#         with:
#           node-version: 20.x

#       - name: Replace Environment Variables
#         run: |
#           node ../scripts/replace-env.js
#         env:
#           FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
#           FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
#           FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
#           FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
#           FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
#           FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
#           FIREBASE_MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID }}
#           DISCORD_REDIRECT_URL: ${{ secrets.DISCORD_REDIRECT_URL }}
#           DISCORD_CLIENT_ID: ${{ secrets.DISCORD_CLIENT_ID }}
#           DISCORD_CLIENT_SECRET: ${{ secrets.DISCORD_CLIENT_SECRET }}
#           DISCORD_GUILD_ID: ${{ secrets.DISCORD_GUILD_ID }}
#           DISCORD_LOGIN_URL: ${{ secrets.DISCORD_LOGIN_URL }}
#           DISCORD_LOCAL_REDIRECT_URL: ${{ secrets.DISCORD_LOCAL_REDIRECT_URL }}
#           DISCORD_LOCAL_CLIENT_ID: ${{ secrets.DISCORD_LOCAL_CLIENT_ID }}
#           DISCORD_LOCAL_CLIENT_SECRET: ${{ secrets.DISCORD_LOCAL_CLIENT_SECRET }}
#           DISCORD_LOCAL_GUILD_ID: ${{ secrets.DISCORD_LOCAL_GUILD_ID }}
#           DISCORD_LOCAL_LOGIN_URL: ${{ secrets.DISCORD_LOCAL_LOGIN_URL }}

#       - name: Install Dependencies
#         run: npm install

#       - name: Build Angular
#         run: npm run build -- --configuration=production

#       - name: Build the app
#         run: |
#           echo "Building the app with Firebase and Discord configs"
#           npm run build -- --configuration production
