name: Deploy Angular to GitHub Pages (Docs)

on:
  push:
    branches: [main]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install gettext per envsubst
        run: sudo apt-get install gettext -y

      - name: Crea environment.prod.ts
        env:
          # Firebase
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          FIREBASE_MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID }}
          # Discord
          DISCORD_CLIENT_ID: ${{ secrets.DISCORD_CLIENT_ID }}
          DISCORD_CLIENT_SECRET: ${{ secrets.DISCORD_CLIENT_SECRET }}
          DISCORD_GUILD_ID: ${{ secrets.DISCORD_GUILD_ID }}
          DISCORD_LOGIN_DISCORD: ${{ secrets.DISCORD_LOGIN_DISCORD }}
          DISCORD_REDIRECT_URL: ${{ secrets.DISCORD_REDIRECT_URL }}
        run: |
          mkdir -p src/environments
          envsubst < src/environments/environment.prod.template.ts > src/environments/environment.prod.ts

      - name: Installa dipendenze
        run: npm ci --no-audit

      - name: Build Angular in docs
        run: |
          npm run build -- --configuration production --base-href /rot/ --output-path docs
          sed 's/<base href="\/rot\/">/<base href="\/">/' docs/index.html > docs/404.html
          touch docs/.nojekyll

      - name: Verifica docs
        run: ls -la docs

      - name: Carica Docs come artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs/'

      - name: Deploy su GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}