on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check if environment.prod.ts exists
        run: |
          if [ ! -f src/environments/environment.prod.ts ]; then
            echo "Error: environment.prod.ts not found!"
            exit 1
          fi

      - name: Set environment variables for Firebase and Discord
        run: |
          firebaseConfig=${{secrets.FIREBASE_DETAILS}}"
          echo "$firebaseConfig"
          discordConfig=${{secrets.DISCORD_DETAILS}}"
          echo "$discordConfig"

      - name: Debug environment variables
        run: |
          echo "firebaseConfig"
          echo "discordConfig"
  
      - name: Install dependencies
        run: |
          npm install -g @angular/cli
          npm install

      - name: Build the app
        run: |
          echo "Building the app with Firebase and Discord configs"
          npm run build -- --configuration production
