name: Deploy Jekyll with GitHub Pages dependencies preinstalled

on:
  push:
    branches: ["main"]  # Questo triggera l'azione quando viene fatto un push su 'main'

  workflow_dispatch:  # Consente l'esecuzione manuale dal tab Actions

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./docs
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout the repository again
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages (main branch)
        id: deployment
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main  # Specifica che il deploy avviene sul branch 'main'
          folder: docs  # Il contenuto generato da Jekyll si trova in './_site'
